name: GGGamingCapstone

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run List Simulator
      run: xcrun simctl list
    - name: Build iOS App
      run: xcodebuild -project GGGamingCapstone/GGGamingCapstone.xcodeproj -scheme "GGGamingCapstone (iOS)" -destination "platform=iOS Simulator,name=iPhone 13 Pro"