name: GGGamingCapstone

on:
  push:
    # branches: [ main ]
  pull_request:
    # branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - uses: actions/checkout@v2
    - name: Run List Simulator
      run: xcrun simctl list
    - name: Build iOS App
      run: xcodebuild -project GGGamingCapstone/GGGamingCapstone.xcodeproj -scheme "GGGamingCapstone" -destination "platform=iOS Simulator,name=iPhone 13 Pro"